### ISSUE TITLE
Endless loop when passing positional argument when it is not defined

### ISSUE THREAD

**Issue by maxmitti** [jgcodes2020/mtap#3]
Executing `./one-arg foo` causes an infinite loop, similarly to #2.

In general, it might be an idea to throw if the end of the for-loop is reached, as it would cause an infinite loop in this case.
At least an unhandled exception would be clearer than an endless loop.

**Comment by jgcodes2020** [comment]
I've added the loop exception, as you suggested. This was also fixed.
