### ISSUE TITLE
Long options get the wrong argument string passed

### ISSUE THREAD

**Issue by maxmitti** [jgcodes2020/mtap#4]
The following example shows the issue:

```C++
int main(int argc, const char* argv[]) {
  mtap::parser(
    option<"--test", 1>([](std::string_view arg) {
      std::cout << "Test: " << arg << "\n";
      std::exit(0);
    })
  ).parse(argc, argv);
}
```

When executing this as `./prog --test foo` it prints `Test: --test` instead of `Test: foo`.

Simply adding `+ 1` in argv[] [here](https://github.com/jgcodes2020/mtap/blob/master/include/mtap/mtap.hpp#L345) seems to do the trick.

**Comment by jgcodes2020** [comment]
Thank you so much for taking the time to test this library.

**Comment by maxmitti** [comment]
I am actually just trying to use mtap and found all of this acidentially.
Anyway I am glad that you appreciate the feedback.
